FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /App

COPY *.sln .
COPY Directory.Packages.props .

RUN mkdir -p src/MathLLMBackend.Presentation \
    src/MathLLMBackend.Core \
    src/MathLLMBackend.DataAccess \
    src/MathLLMBackend.Domain \
    src/MathLLMBackend.GeolinClient

COPY src/MathLLMBackend.Presentation/MathLLMBackend.Presentation.csproj ./src/MathLLMBackend.Presentation/
COPY src/MathLLMBackend.Core/MathLLMBackend.Core.csproj ./src/MathLLMBackend.Core/
COPY src/MathLLMBackend.DataAccess/MathLLMBackend.DataAccess.csproj ./src/MathLLMBackend.DataAccess/
COPY src/MathLLMBackend.Domain/MathLLMBackend.Domain.csproj ./src/MathLLMBackend.Domain/
COPY src/MathLLMBackend.GeolinClient/MathLLMBackend.GeolinClient.csproj ./src/MathLLMBackend.GeolinClient/

RUN dotnet restore

COPY . .

# Install EF Core tools
RUN dotnet tool install --global dotnet-ef

# Set the entrypoint to run migrations
ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/MathLLMBackend.DataAccess", "--startup-project", "src/MathLLMBackend.Presentation"] 