name: Video Docker

on:
  push:
    branches: ["master"]
    paths:
      - "services/video/**"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-suffix: video
      context: ./services/video
      dockerfile: ./services/video/Dockerfile
      push: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
